// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kspzfafzwfgtuklnqqrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzcHpmYWZ6d2ZndHVrbG5xcXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzODEwOTMsImV4cCI6MjA4Njk1NzA5M30.Vei69TKeZY2lkxce8XHsyxSBwWN7k-CYi6TZLXNJFak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});